/* Firebird UI Test Database Fixtures
 * Creates test objects that the UI tests verify exist in the navigator.
 */

/* Tables */
CREATE TABLE TEST_CUSTOMER (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TEST_ORDER (
    ID INTEGER NOT NULL PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL REFERENCES TEST_CUSTOMER(ID),
    ORDER_DATE DATE NOT NULL,
    TOTAL DECIMAL(15,2)
);

/* Sequences */
CREATE SEQUENCE SEQ_TEST_CUSTOMER;
CREATE SEQUENCE SEQ_TEST_ORDER;

/* View */
CREATE VIEW V_TEST_CUSTOMER_ORDERS AS
SELECT c.ID, c.NAME, COUNT(o.ID) AS ORDER_COUNT, COALESCE(SUM(o.TOTAL), 0) AS TOTAL_AMOUNT
FROM TEST_CUSTOMER c
LEFT JOIN TEST_ORDER o ON o.CUSTOMER_ID = c.ID
GROUP BY c.ID, c.NAME;

/* Stored Procedure */
SET TERM !! ;
CREATE OR ALTER PROCEDURE SP_UITEST_SETTERM
RETURNS (RESULT VARCHAR(50))
AS
BEGIN
  RESULT = 'SET_TERM_OK';
  SUSPEND;
END !!
SET TERM ; !!

/* Sample data */
INSERT INTO TEST_CUSTOMER (ID, NAME, EMAIL) VALUES (1, 'Alice', 'alice@test.com');
INSERT INTO TEST_CUSTOMER (ID, NAME, EMAIL) VALUES (2, 'Bob', 'bob@test.com');
INSERT INTO TEST_ORDER (ID, CUSTOMER_ID, ORDER_DATE, TOTAL) VALUES (1, 1, CURRENT_DATE, 150.00);
INSERT INTO TEST_ORDER (ID, CUSTOMER_ID, ORDER_DATE, TOTAL) VALUES (2, 1, CURRENT_DATE, 250.00);
INSERT INTO TEST_ORDER (ID, CUSTOMER_ID, ORDER_DATE, TOTAL) VALUES (3, 2, CURRENT_DATE, 75.50);

COMMIT;
